Repository AI-Play/ML-Funcs, pull requests merged in 2022-03, with the labels that each got.

#75 [FeatureMade] 결측치 & 에러메세지
  functions/__init__.py
  functions/eda.py
  functions/preprocessing.py
  functions/processing.py
  main.py
  visualization/AI_plot.py
Labels: 분류: 버그

#78 [FeatureMade] 20220312 error_check 기능 추가
  .gitignore
  functions/__init__.py
  functions/eda.py
  functions/internal_func.py
  functions/preprocessing.py
  functions/processing.py
  main.py
Labels: 분류: 기능 구현, 분류: 버그

#81 [BUG FIX]20220313 train_test_split 버그 수정
  functions/internal_func.py
  functions/preprocessing.py
Labels: 분류: 버그

#79 [BUG] main.py visualization method get->post
  main.py
  visualization/AI_plot.py
Labels: 분류: 버그

#82 [FeatureMade] postgres func_log 저장 기능 20220320
  functions/internal_func.py
Labels: 분류: 기능 구현

#83 [FeatureMade] .env setting updated
  config.py
  functions/internal_func.py
Labels: 분류: 기능 구현

#84 [FeatureMade] CORS Origins updated
  main.py
Labels: 분류: 기능 구현

#85 requirements.txt updated
  requirements.txt
Labels: 분류: 문서화
