Repository AI-Play/ML-Funcs, pull requests merged in 2022-02, with the labels that each got.

#42 [FeatureMade] data2json - 20220218
  .gitignore
  README.md
  functions/__init__.py
  functions/data2json.py
  main.py
  requirements.txt
Labels: 분류: 기능 구현

#43 [FeatureMade] 데이터 조회, 데이터 형태확인, 데이터 타입확인, 데이터 분포 확인, 컬럼 목록 조회, 컬럼 내 고윳값 조회, 데이터 결측치 확인, 데이터 상관관계 확인, 데이터 프레임 행 열 자리 바꾸기
  functions/__init__.py
  functions/eda.py
  functions/processing.py
  main.py
Labels: 분류: 기능 구현

#44 [FeatureMade]데이터 그룹핑, 행 또는 열 제거, 데이터 결측치 제거, 컬럼명 변경, 데이터프레임 정렬
  functions/__init__.py
  functions/eda.py
  functions/processing.py
  main.py
Labels: 분류: 기능 구현

#45 [BUG] CORS setting added
  main.py
  requirements.txt
Labels: 분류: 기능 구현, 분류: 버그, 우선 순위: 상

#46 [FeatureMade] merge & concat
  functions/__init__.py
  functions/processing.py
  main.py
Labels: 분류: 기능 구현

#48 "[FeatureMade] Box Plot"
  functions/AI_plot.py
  functions/__init__.py
  functions/data2json.py
  functions/templates/plot_test.html
  main.py
  test.html
Labels: 분류: 기능 구현, 우선 순위: 중

#49 to_json 수정
  functions/__init__.py
  functions/eda.py
  functions/processing.py
  main.py
Labels: 분류: 버그

#50 [버그 수정]20220221 to_json
  functions/data2json.py
Labels: 분류: 버그

#51 [버그 수정] 20220221 main.py
  functions/__init__.py
  main.py
Labels: 분류: 버그

#52 [FeatureMade] 20220222 loc, iloc, col/condition 이경희
  functions/__init__.py
  functions/eda.py
  functions/processing.py
Labels: 분류: 기능 구현

#54 [FeadtureEdit] 20220222 groupby, col_condition, unique 수정
  functions/__init__.py
  functions/eda.py
  functions/processing.py
  main.py
Labels: 분류: 기능 추가 요청

#55 [FeatureEdit] 20220222 sort URL 변경
  main.py
Labels: 분류: 기능 추가 요청

#56 "[FeatureMade] hist, count, scatter"
  .gitignore
  functions/AI_plot.py
  functions/__init__.py
  main.py
  visualization/AI_plot.py
  visualization/__init__.py
  visualization/templates/plot_test.html
Labels: 분류: 기능 구현, 우선 순위: 중

#57 [FeatureMade] 20220223 컬럼 추가 및 변경 이경희
  functions/eda.py
  functions/preprocessing.py
  functions/processing.py
Labels: 분류: 기능 구현

#61 20220223 get_na, get_corr 수정
  functions/eda.py
Labels: 분류: 기능 추가 요청, 분류: 버그

#63 [FeatureMade] 20220224 피쳐타겟분리, train,test분리, None이 입력 안되는 이슈 해결
  functions/__init__.py
  functions/eda.py
  functions/preprocessing.py
  functions/processing.py
  main.py
  requirements.txt
Labels: 분류: 기능 구현, 분류: 버그

#68 [BUG/FeatureMade] 시각화 관련 함수의 return 방식 등 수정
  main.py
  visualization/AI_plot.py
Labels: 분류: 기능 구현, 분류: 버그

#71 [버그 수정] 20220228 groupby, set_colulms size 제거, train_valid_split 추가
  functions/__init__.py
  functions/eda.py
  functions/preprocessing.py
  functions/processing.py
  main.py
Labels: 분류: 기능 추가 요청, 분류: 버그
